-- EQUITY AND FIXED INCOME CLIENTS --
DECLARE @FUNDCUSIP CHAR(9)
SET	@FUNDCUSIP = 'L5773B106'

DECLARE @HISTDATE DATE
DECLARE @DAYSBACK INTEGER
DECLARE @DAYSAHEAD INTEGER

SET @HISTDATE = '2014-10-31'	-- PERSPECTIVE DATE
SET @DAYSBACK = -30				--THE NUMBER OF DAYS PRIOR TO THE @HISTDATE THAT HOLDINGS WOULD BE CONSIDERED VALID
SET @DAYSAHEAD = 0				--THE NUMBER OF DAYS AFTER THE @HISTDATE THAT HOLDINGS WOULD BE CONSIDERED VALID
;
WITH ALL_FUND_HOLDINGS AS (
	SELECT FACTSET_FUND_ID, REPORT_DATE, SECURITY_ID, SECURITY_NAME, SECURITY_TYPE, ADJ_HOLDING, ADJ_MV, REPORTED_HOLDING, REPORTED_MV
	FROM (	
		--DETAIL HOLDINGS
		SELECT 
			  D.FACTSET_FUND_ID
			, D.REPORT_DATE, D.FSYM_ID AS SECURITY_ID
			, OC.SECURITY_NAME, SECURITY_TYPE = CASE WHEN OC.UNIVERSE_TYPE ='EQ' THEN 'EQUITY' ELSE 'FIXED INCOME' END 
			, D.ADJ_HOLDING, D.ADJ_MV
			, D.REPORTED_HOLDING
			, D.REPORTED_MV
		FROM OWN_V5.OWN_FUND_DETAIL D
		JOIN OWN_V5.OWN_SEC_COVERAGE OC ON OC.FSYM_ID = D.FSYM_ID

		UNION
		--GENERIC HOLDINGS
		SELECT 
			  G.FACTSET_FUND_ID
			, G.REPORT_DATE
			, G.GENERIC_ID AS SECURITY_ID
			, M.GENERIC_ID_DESC AS SECURITY_NAME
			, SECURITY_TYPE = 'GENERICS'
			, NULL AS ADJ_HOLDING
			, NULL AS ADJ_MV
			, NULL AS REPORTED_HOLDING
			, G.REPORTED_MV
		FROM OWN_V5.OWN_FUND_GENERIC G
		JOIN REF_V2.GENERIC_ID_MAP M ON M.GENERIC_ID_CODE = G.GENERIC_ID
		) A )

SELECT H.FACTSET_FUND_ID AS 'FACTSET FUND ID'
, EF.ENTITY_PROPER_NAME AS 'FUND NAME' 
, F.FACTSET_INST_ENTITY_ID AS 'MANAGING INSTITUTION ID'
, E.ENTITY_PROPER_NAME AS 'MANAGING INSTITUTION NAME'
, H.SECURITY_ID AS 'SECURITY ID'
, CU.CUSIP AS 'CUSIP'
, H.SECURITY_NAME AS 'SECURITY NAME'
, H.SECURITY_TYPE AS 'SECURITY TYPE'
, H.REPORT_DATE AS 'REPORT DATE'
, H.ADJ_HOLDING AS 'ADJUSTED HOLDING'
, H.ADJ_MV AS 'ADJUSTED MARKET VALUE'
, H.REPORTED_HOLDING AS 'REPORTED HOLDING'
, H.REPORTED_MV AS 'REPORTED MARKET VALUE'
FROM ALL_FUND_HOLDINGS H
JOIN OWN_V5.OWN_ENT_FUNDS F ON F.FACTSET_FUND_ID = H.FACTSET_FUND_ID
JOIN SYM_V1.SYM_ENTITY E ON E.FACTSET_ENTITY_ID = F.FACTSET_INST_ENTITY_ID
JOIN SYM_V1.SYM_ENTITY EF ON EF.FACTSET_ENTITY_ID = H.FACTSET_FUND_ID
LEFT JOIN SYM_V1.SYM_COVERAGE CO ON CO.FSYM_ID = H.SECURITY_ID
LEFT JOIN SYM_V1.SYM_CUSIP CU ON CU.FSYM_ID = CO.FSYM_SECURITY_ID

JOIN --SELECT THE LATEST REPORT DATE FOR THE FUND WITHIN THE WINDOW
	(	SELECT I.FACTSET_FUND_ID, MAX(F.REPORT_DATE) MAX_REPORT_DATE
		FROM SYM_V1.SYM_CUSIP C
		JOIN SYM_V1.SYM_COVERAGE SC ON SC.FSYM_ID = C.FSYM_ID
		JOIN OWN_V5.OWN_ENT_FUND_IDENTIFIERS I ON I.FUND_IDENTIFIER = SC.FSYM_SECURITY_ID
		JOIN OWN_V5.OWN_ENT_FUND_FILING_HIST F ON F.FACTSET_FUND_ID = I.FACTSET_FUND_ID
		WHERE C.CUSIP = @FUNDCUSIP AND F.REPORT_DATE BETWEEN DATEADD(DD,@DAYSBACK,@HISTDATE) AND DATEADD(DD,@DAYSAHEAD,@HISTDATE)
		GROUP BY I.FACTSET_FUND_ID
	) A ON A.MAX_REPORT_DATE = H.REPORT_DATE AND A.FACTSET_FUND_ID = H.FACTSET_FUND_ID
ORDER BY H.FACTSET_FUND_ID , H.REPORTED_MV DESC